#!/bin/sh
#
# A hook script to verify MATLAB code using CC4M.
# Called by "git commit" with no arguments.

###################################################################################################
# 			                    			                 								      #
# 			                   			Configurable settings								      #
#                            			Adapt to your situation      						      #
# 			                    			                 								      #
###################################################################################################

# Location of the MATLAB installatio to use.
matlabRoot="/c/Program Files/MATLAB/R2025b"

# From the predefined configurations, use the "MonkeyProof Coding Standard for MATLAB".
configFile=MonkeyProofMATLABCodingStandard

# List of extensions to include.
supportedExtensions="\.m$|\.mlx$|\.slx$|\.mlapp$|\.mdl$"

# Only rules with severity level equal to or higher than "severityAllow" will be included.
# Violations of rules with severity level equal to or higher than "severityBlock" will block the commit.
severityBlock=3
severityAllow=10

# License-related settings
# In case of a floating license:
#export MONKEYPROOF_FLOATING_LICENSE_SERVER=<server:port>
# In case of a license file:
#export MONKEYPROOF_LICENSE_FILE_FOLDER=<folder where license file is saved.>

###################################################################################################
# 			                    			                 								      #
# 			                    			Generic settings								      #
#                            			Only adapt when you are sure						      #
# 			                    			                 								      #
###################################################################################################
 
matlabExe="$matlabRoot/bin/matlab"
matlabInitCmd="addpath(monkeyproof.cc4m.utils.userpath());"
if [[ "$matlabRoot" == *"R2026a" ]];then 
	subdir="26.1"
elif [[ "$matlabRoot" == *"R2025b" ]];then 
	subdir="25.2"
elif [[ "$matlabRoot" == *"R2025a" ]];then 
	subdir="25.1"
elif [[ "$matlabRoot" == *"R2024b" ]];then 
	subdir="24.2"
elif [[ "$matlabRoot" == *"R2024a" ]];then 
	subdir="23.2"
elif [[ "$matlabRoot" == *"R2023b" ]];then 
	subdir="23.1"
elif [[ "$matlabRoot" == *"R2023a" ]];then 
	subdir="9.14"	
elif [[ "$matlabRoot" == *"R2022b" ]];then 
	subdir="9.13"
elif [[ "$matlabRoot" == *"R2022a" ]];then 
	subdir="9.12"	
elif [[ "$matlabRoot" == *"R2021b" ]];then 
	subdir="9.11"
elif [[ "$matlabRoot" == *"R2021a" ]];then 
	subdir="9.10"	
elif [[ "$matlabRoot" == *"R2020b" ]];then 
	subdir="9.9"
elif [[ "$matlabRoot" == *"R2020a" ]];then 
	subdir="9.8"		
else
	subdir="25.2"
fi


if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        homeFolder=$HOME
elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
		homeFolder=$home
elif [[ "$OSTYPE" == "cygwin" ]]; then
        # POSIX compatibility layer and Linux environment emulation for Windows
		homeFolder=$USERPROFILE
elif [[ "$OSTYPE" == "msys" ]]; then
        # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
		homeFolder=$USERPROFILE
elif [[ "$OSTYPE" == "freebsd"* ]]; then
        homeFolder=$HOME
else
        # Unknown - assume linux
		homeFolder=$HOME
fi


envdir=$homeFolder/Documents/MATLAB/cc4m/python/$subdir
e

# Git repository root folder.
gitRootFolder=$(git rev-parse --show-toplevel)

# Activate Python environment.
. $envdir/Scripts/activate

echo "adapt PythonPath"
export PYTHONPATH
PYTHONPATH="$envdir/Lib;$PYTHONPATH"

# Only rules with severity level equal to or higher than "severityLevelBoundary" will be included.
severityLevelBoundary=10

# Initialize variables.
gitFullFiles=
count=0

## The hook.
# Loop over files to commit, just keep files to check.
for file in $(git diff --cached --name-only --diff-filter=ACM); do
  if echo "$file" | grep -qE "$supportedExtensions"; then
    echo "$file contains MATLAB code."
    if [ 1 -eq $count ]
	then
		gitFullFiles=''$gitFullFiles,''
	fi
	gitFullFiles=$gitFullFiles''"$gitRootFolder/$file"''
	count=1
  else
	echo "$file not checked."
  fi
done

if test $count -eq 0 
then
	echo "No MATLAB files to check."
	exit 0
fi

echo "Checking MATLAB files."
echo " "

matlabOutput=$(python -m cc4m_githooks.precommit "$envdir/Lib" "$matlabExe" "$gitRootFolder" "precommit_example('$gitFullFiles', '$configFile', severityBlock=$severityBlock, severityAllow=$severityAllow)")
errorlevel=$?
echo "$errorlevel"

if test $errorlevel -eq 0
then
	echo ok
	exit 0
else
	if test $errorlevel -eq 1
	then
	    echo "Blocking violations found - commit canceled." 
	else
		echo "Do you wish to install this program?"
		select yn in "Yes" "No"; do
			case $yn in
				Yes ) make install; break;;
				No ) exit;;
			esac
		done
	fi
	
fi

function ask_yes_or_no() {
    read -p "$1 ([y]es or [N]o): "
    case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
        y|yes) echo "yes" ;;
        *)     echo "no" ;;
    esac
}