#!/bin/sh
#
# A hook script to verify MATLAB code using CC4M.
# Called by "git commit" with no arguments.

## Configurable settings
# Location of the MATLAB installatio to use.
matlabRoot="/c/Program Files/MATLAB/R2025b"

# From the predefined configurations, use the "MonkeyProof Coding Standard for MATLAB".
configFile=MonkeyProofMATLABCodingStandard

# List of extensions to include.
supportedExtensions="\.m$|\.mlx$|\.slx$|\.mlapp$|\.mdl$"

## Generic settings
matlabExe="$matlabRoot/bin/matlab"
matlabInitCmd="addpath(monkeyproof.cc4m.utils.userpath())";
envdir=$USERPROFILE/Documents/MATLAB/cc4m/python/25.2

# Git repository root folder.
gitRootFolder=$(git rev-parse --show-toplevel)

# Activate Python environment.
. $envdir/Scripts/activate

echo "adapt PythonPath"
export PYTHONPATH
PYTHONPATH="$envdir/Lib;$PYTHONPATH"

# Only rules with severity level equal to or higher than "severityLevelBoundary" will be included.
severityLevelBoundary=10

# Initialize variables.
gitFullFiles=
count=0

## The hook.
# Loop over files to commit, just keep files to check.
for file in $(git diff --cached --name-only --diff-filter=ACM); do
  if echo "$file" | grep -qE "$supportedExtensions"; then
    echo "$file contains MATLAB code."
    if [ 1 -eq $count ]
	then
		gitFullFiles=''$gitFullFiles,''
	fi
	gitFullFiles=$gitFullFiles''"$gitRootFolder/$file"''
	count=1
  else
	echo "$file not checked."
  fi
done

if test $count -eq 0 
then
	echo "No MATLAB files to check."
	exit 0
fi

echo "Checking MATLAB files."
echo " "

matlabOutput=$(python -m cc4m_githooks.precommit "$envdir/Lib" "$matlabExe" "$gitRootFolder" "precommit_example('$gitFullFiles', '$configFile', severityBlock=$severityBlock, severityAllow=$severityAllow)")
errorlevel=$?
echo "$errorlevel"

if test $errorlevel -eq 0
then
	echo ok
	exit 0
else
	if test $errorlevel -eq 1
	then
	    echo "Blocking violations found - commit canceled." 
	else
		echo "Do you wish to install this program?"
		select yn in "Yes" "No"; do
			case $yn in
				Yes ) make install; break;;
				No ) exit;;
			esac
		done
	fi
	
fi

function ask_yes_or_no() {
    read -p "$1 ([y]es or [N]o): "
    case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
        y|yes) echo "yes" ;;
        *)     echo "no" ;;
    esac
}